import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// FILE: client/src/components/left-panel/SelectionBar.tsx
// PURPOSE: Slide-up bar at bottom of entity list showing selected count + "View Consolidated"
// USED BY: client/src/components/left-panel/LeftPanel.tsx
// EXPORTS: SelectionBar
import { AnimatePresence, motion } from 'framer-motion';
export function SelectionBar({ selectedCount, onViewConsolidated, onClear }) {
    return (_jsx(AnimatePresence, { children: selectedCount > 0 && (_jsxs(motion.div, { initial: { y: 57, opacity: 0 }, animate: { y: 0, opacity: 1 }, exit: { y: 57, opacity: 0 }, transition: { type: 'spring', stiffness: 400, damping: 30 }, className: "\n            flex h-[57px] items-center justify-between\n            border-t border-[var(--color-gold-muted)]\n            bg-[var(--color-bg-page)] px-[var(--spacing-2xl)] py-[var(--spacing-base)]\n            backdrop-blur-[8px]\n          ", children: [_jsxs("div", { className: "flex items-center gap-[var(--spacing-sm)]", children: [_jsxs("svg", { width: "14", height: "14", viewBox: "0 0 14 14", fill: "none", "aria-hidden": "true", children: [_jsx("rect", { x: "1", y: "1", width: "12", height: "12", rx: "3", stroke: "var(--color-gold-primary)", strokeWidth: "1.5" }), _jsx("path", { d: "M4 7L6 9L10 5", stroke: "var(--color-gold-primary)", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" })] }), _jsxs("span", { className: "text-[11px] font-medium text-[var(--color-text-secondary)]", children: [selectedCount, " selected"] })] }), _jsxs("div", { className: "flex items-center gap-[var(--spacing-md)]", children: [_jsx("button", { type: "button", onClick: onClear, className: "text-[11px] text-[var(--color-text-muted)] underline transition-colors duration-100 hover:text-[var(--color-text-secondary)]", children: "Clear" }), _jsx("button", { type: "button", onClick: onViewConsolidated, className: "\n                h-[36px] rounded-[var(--radius-base)] bg-[var(--color-dark)]\n                px-[var(--spacing-lg)] py-[5px] text-[11px] font-medium text-white\n                transition-colors duration-150 hover:bg-[var(--color-dark-hover)]\n              ", children: "View Consolidated" })] })] })) }));
}
