import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatCurrency, formatPercent } from '@shared/utils/formatting';
import { AnimatedNumber } from '../shared/AnimatedNumber';
import { YoYBarChart } from './YoYBarChart';
export function HeroRevenueCard({ kpis, monthlyRevenue }) {
    const changePercent = kpis.revenueChangePercent;
    const isPositive = changePercent !== null && changePercent >= 0;
    const trendColor = isPositive ? 'var(--color-green)' : 'var(--color-red)';
    return (_jsxs("div", { className: "flex flex-col rounded-[var(--radius-3xl)] bg-[var(--color-bg-card)] px-[var(--spacing-3xl)] py-[var(--spacing-2xl)] shadow-[var(--shadow-card)]", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[11px] font-medium text-[#888]", children: "Total Revenue (12 months)" }), _jsx("span", { className: "tabular-nums text-[30px] font-[800] leading-tight tracking-[-1px] text-[var(--color-text-primary)]", style: { fontFeatureSettings: "'tnum'" }, children: _jsx(AnimatedNumber, { value: kpis.totalRevenue, formatter: (n) => formatCurrency(Math.round(n)) }) }), changePercent !== null && (_jsxs("span", { className: "text-[12px] font-medium", style: { color: trendColor }, children: [formatPercent(changePercent, { showSign: true }), " vs previous year"] }))] }), _jsxs("div", { className: "flex flex-col items-end", children: [_jsx("span", { className: "text-[10px] font-normal text-[var(--color-text-faint)]", children: "Previous Year" }), _jsx("span", { className: "text-[16px] font-semibold text-[var(--color-text-faint)]", children: _jsx(AnimatedNumber, { value: kpis.prevYearRevenue, formatter: (n) => formatCurrency(Math.round(n)) }) })] })] }), _jsxs("div", { className: "mt-[var(--spacing-md)] flex gap-[var(--spacing-3xl)]", children: [_jsx(SubItem, { label: "This Quarter", value: kpis.thisQuarterRevenue }), _jsx(SubItem, { label: "Best Month", value: kpis.bestMonth.amount, suffix: kpis.bestMonth.name }), _jsx(SubItem, { label: "Previous Year", value: kpis.prevYearRevenue })] }), _jsx("div", { className: "mt-[var(--spacing-lg)]", children: _jsx(YoYBarChart, { data: monthlyRevenue }) })] }));
}
function SubItem({ label, value, suffix, }) {
    return (_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[11px] font-normal text-[#888]", children: label }), _jsxs("span", { className: "text-[15px] font-semibold text-[var(--color-text-secondary)]", children: [formatCurrency(value), suffix && (_jsxs("span", { className: "ml-1 text-[11px] font-normal text-[#888]", children: ["(", suffix, ")"] }))] })] }));
}
